
/*SQL Script to create table structure for Hospital Admin*/
CREATE TABLE HOSPITAL_ADMIN
(
    ADMIN_ID INT NOT NULL IDENTITY(100,1),
    ADMIN_NAME VARCHAR(30) NOT NULL,
    CONTACT_NO INT NOT NULL,
    EMAIL_ID VARCHAR(50) NOT NULL UNIQUE,
	CONSTRAINT HOSPITAL_ADMIN_PK PRIMARY KEY (ADMIN_ID)
);

/*SQL Script to create table structure for Lab*/
CREATE TABLE LAB
(
    LAB_ID INT NOT NULL IDENTITY(1000,1),
    LAB_NAME VARCHAR(30) NOT NULL,
	LAB_TYPE VARCHAR(30) NOT NULL,
    LAB_DESCRIPTION VARCHAR(50) NOT NULL,
	ADMIN_ID INT NOT NULL,
    CONSTRAINT LAB_PK PRIMARY KEY (LAB_ID),
	CONSTRAINT LAB_FK FOREIGN KEY (ADMIN_ID) REFERENCES HOSPITAL_ADMIN(ADMIN_ID)
);

/*Insert Scripts for HOSPITAL_ADMIN*/

INSERT INTO HOSPITAL_ADMIN VALUES('Brandy Hagenes', 1978253236, 'brandy.hagenes@yahoo.com');
INSERT INTO HOSPITAL_ADMIN VALUES('Geraldo Schumm', 9498602713, 'geraldo.schumm@yahoo.com');
INSERT INTO HOSPITAL_ADMIN VALUES('Jenice Satterfield', 6052122437, 'jenice.satterfield@yahoo.com');
INSERT INTO HOSPITAL_ADMIN VALUES('Cecille Aufderhar', 5679733830, 'cecille.aufderhar@yahoo.com');
INSERT INTO HOSPITAL_ADMIN VALUES('Cameron Schinner', 3192189003, 'cameron.schinner@yahoo.com');
INSERT INTO HOSPITAL_ADMIN VALUES('Daron Johns', 5013366101, 'daron.johns@yahoo.com');