/*Create view for fetching out patient hospital details*/
CREATE VIEW PATIENT_HOSPITAL_DETAILS
AS
       SELECT P.PATIENT_ID,(P.FIRST_NAME +' '+ P.MIDDLE_NAME +' '+ P.LAST_NAME) AS PATIENT_NAME,
	   CASE WHEN A.PATIENT_TYPE= 'I' THEN 'In-Patient' 
	   WHEN A.PATIENT_TYPE = 'O' THEN 'Out-Patient' END AS PATIENT_TYPE, 
	   DR.DOCTOR_ID, (DR.FIRST_NAME +' '+ DR.MIDDLE_NAME +' '+ DR.LAST_NAME) AS DOCTOR_NAME,
	   DT.DEPT_ID, DT.DEPT_NAME
       FROM APPOINTMENT_SCHEDULING A JOIN PATIENT P
	   ON A.PATIENT_ID = P.PATIENT_ID JOIN DOCTOR_SCHEDULE DS 
	   ON A.DOCSCHEDULE_ID = DS.DOCSCHEDULE_ID JOIN DOCTOR DR
	   ON DS.DOCTOR_ID = DR.DOCTOR_ID JOIN DEPARTMENT DT
	   ON DT.DEPT_ID = DR.DEPT_ID;
GO

/*Create view for Doctor count as per Department*/
CREATE VIEW DEPARTMENT_DOCTOR_COUNT 
AS 
	   SELECT DT.DEPT_ID,DT.DEPT_NAME, COUNT(DR.DOCTOR_ID) AS TOTAL_DOCTORS
       FROM DOCTOR DR JOIN DEPARTMENT DT
	   ON DR.DEPT_ID = DT.DEPT_ID
	   GROUP BY DT.DEPT_ID, DT.DEPT_NAME;

GO 

/*Create view for Patient count as per Department*/
CREATE VIEW DEPARTMENT_PATIENT_COUNT 
AS 
	   SELECT DT.DEPT_ID,DT.DEPT_NAME, COUNT(P.PATIENT_ID) AS TOTAL_PATIENTS
       FROM APPOINTMENT_SCHEDULING A JOIN PATIENT P
	   ON A.PATIENT_ID = P.PATIENT_ID JOIN DOCTOR_SCHEDULE DS
	   ON DS.DOCSCHEDULE_ID = A.DOCSCHEDULE_ID JOIN DOCTOR DR
	   ON DS.DOCTOR_ID = DR.DOCTOR_ID JOIN DEPARTMENT DT
	   ON DR.DEPT_ID = DT.DEPT_ID
	   GROUP BY DT.DEPT_ID, DT.DEPT_NAME;
